version: "3.3"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    ports:
      - 3001:3001
    networks:
      - default
      - traefik-proxy
    volumes:
      - ${CONTAINERS_DIR}/uptime-kuma-data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime-kuma.rule=Host(`uptime-kuma.local.${DOMAIN}`)"
    restart: unless-stopped

networks:
  default:
    name: uptime-kuma
  traefik-proxy:
    name: ${TRAEFIK_NETWORK}
    external: true
